### ISSUE TITLE
Everyone who used this got banned lol.

### ISSUE THREAD

**Issue by nvnprogram** [supremetakoyaki/ShiverBot#4]
Don’t claim it’s “very unlikely to ban just cuz I didn’t get banned for a few days”. It’s like saying “walking in the middle of the road is safe cuz I haven’t been hit by a car yet”, cuz now everyone got hit by the car, or a ban in this case.

**Comment by nvnprogram** [comment]
*under used I mean used for editing their save, stuff like money, chunks, Sheldon licenses or whatever

**Comment by supremetakoyaki** [comment]
Y'all knew the risks. There was never a guarantee that it was safe. It's in the readme and it was your choice.

Not everyone got banned, as there are reports of people who used the tool and weren't part of the banwave, but yeah.

Because even the most harmless edit (chunks) was cause for a ban, I will update the program to only have the gear seed viewer and the post printer, which don't edit anything.

**Comment by nvnprogram** [comment]
I didn’t use it lol. Also, I meant the fact that you said “minimal risks” when it’s in fact very likely to be detected cuz the entire save is literally on n’s servers.
